In [29]:
import sys
from pathlib import Path
import pandas as pd

PROJECT_ROOT = r"c:\Users\murja\Desktop\SIRA"
if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)

In [30]:
from src.data_loader import DataLoader
from src.eda import DataExplorer

In [31]:
loader = DataLoader()

In [32]:
df = loader.load_data()

In [33]:
explorer = DataExplorer()

In [34]:
explorer.show_missing_values(df)

missing values:
['incident_id', 'report_text', 'location', 'reported_by']

loader = DataLoader()
explorer = DataEplorer()
df = loader.load_data()

In [35]:
df_empty = df[df["report_text"] == ""]
df_empty_count = df_empty.shape[0]
df_empty_count

0

In [36]:
explorer.duplicate_rows(df)

'Number of duplicate rows: 5'

In [37]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5      True
6      True
7      True
8      True
9      True
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
dtype: bool

In [38]:
df =["report_text"]

In [41]:
# 1. Let's look at the type of data inside the list
print("Type of data:", type(df))
if len(df) > 0:
    print("\nFirst element in the list looks like:")
    print(df[0])

Type of data: <class 'list'>

First element in the list looks like:
report_text

In [46]:
import pandas as pd

if isinstance(df, list):
    column_name = df[0]
    data_rows = df[1:]  
    df = pd.DataFrame(data_rows, columns=[column_name])

# 1. Check the total number of rows available
print(f"Total rows in DataFrame: {len(df)}")

# 2. View the first few rows safely using .head() instead of .loc
print("\nFirst few rows of your data:")
print(df.head())

Total rows in DataFrame: 0

First few rows of your data:
Empty DataFrame
Columns: [report_text]
Index: []

In [20]:
df

,incident_id,report_text,location,reported_by
0,1,Pressure leak detected on Pipeline 7.,Pipeline 7,John
1,2,Worker slipped near drilling platform.,Platform A,Aisha
2,3,Gas detector triggered alarm.,Plant B,Michael
3,4,Small oil spill observed near storage tank.,Tank Farm,David
4,5,Emergency shutdown initiated after abnormal vi...,Refinery,Grace
5,1,Pressure leak detected on Pipeline 7.,Pipeline 7,John
6,2,Worker slipped near drilling platform.,Platform A,Aisha
7,3,Gas detector triggered alarm.,Plant B,Michael
8,4,Small oil spill observed near storage tank.,Tank Farm,David
9,5,Emergency shutdown initiated after abnormal vi...,Refinery,Grace
10,6,NaN,Pipeline 8,John
11,7,Pressure leak detected on Pipeline 7.,Pipeline 7,John
12,8,gas detector triggered alarm.,Plant B,Michael
13,9,Gas detector triggred alarm.,Plant B,Michael
14,10,Worker slipped near drilling platform.,Platform A,Aisha
15,11,NaN,Tank Farm,David
16,12,PRESSURE LEAK DETECTED ON PIPELINE 7.,Pipeline 7,John
17,13,Pressure leak detected on Pipeline 7.,Pipeline 7,John
18,14,Worker slipped near drilling platform.,Platform A,NaN
19,15,Emergency shutdown initiated after abnormal vi...,Refinery,Grace

In [19]:
df.head()

,incident_id,report_text,location,reported_by
0,1,Pressure leak detected on Pipeline 7.,Pipeline 7,John
1,2,Worker slipped near drilling platform.,Platform A,Aisha
2,3,Gas detector triggered alarm.,Plant B,Michael
3,4,Small oil spill observed near storage tank.,Tank Farm,David
4,5,Emergency shutdown initiated after abnormal vi...,Refinery,Grace

In [21]:
corrections = {
    "triggred": "triggered"
}

In [22]:
corrections.items()

dict_items([('triggred', 'triggered')])

In [25]:
for wrong, correct in corrections.items():
    df["report_text"] = df["report_text"].str.replace(
        wrong,
        correct,
        regex=False
    )

In [26]:
df.head(15)

,incident_id,report_text,location,reported_by
0,1,Pressure leak detected on Pipeline 7.,Pipeline 7,John
1,2,Worker slipped near drilling platform.,Platform A,Aisha
2,3,Gas detector triggered alarm.,Plant B,Michael
3,4,Small oil spill observed near storage tank.,Tank Farm,David
4,5,Emergency shutdown initiated after abnormal vi...,Refinery,Grace
5,1,Pressure leak detected on Pipeline 7.,Pipeline 7,John
6,2,Worker slipped near drilling platform.,Platform A,Aisha
7,3,Gas detector triggered alarm.,Plant B,Michael
8,4,Small oil spill observed near storage tank.,Tank Farm,David
9,5,Emergency shutdown initiated after abnormal vi...,Refinery,Grace
10,6,NaN,Pipeline 8,John
11,7,Pressure leak detected on Pipeline 7.,Pipeline 7,John
12,8,gas detector triggered alarm.,Plant B,Michael
13,9,Gas detector triggered alarm.,Plant B,Michael
14,10,Worker slipped near drilling platform.,Platform A,Aisha

In [48]:
print(df.isnull().sum())
print(df.duplicated().sum())
print(df.head())

report_text    0
dtype: int64
0
Empty DataFrame
Columns: [report_text]
Index: []