In [1]:
import pandas as pd

# Load the raw dataset into the variable 'df'
df = pd.read_csv("data/incident_reports_1000.csv")

df.head()

,incident_id,report_text,location,reported_by,department,severity,incident_type,report_date,shift,status
0,1,Pressure leak detected on Pipeline 7 during ro...,Platform B,Aisha,Instrumentation,High,Leak,2025-09-30,Day,Open
1,2,NaN,Compressor Station,Mary,Utilities,Low,Inspection,2025-12-15,Day,Closed
2,3,NaN,Tank Farm,Mary,Utilities,Medium,Slip/Fall,2025-09-09,Day,Open
3,4,Smoke observed from electrical control panel.,Refinery,Joy,Production,High,Electrical,2026-01-22,Day,Open
4,5,NaN,Gas Processing Unit,Samuel,Production,Medium,Equipment Failure,2025-02-14,Day,Closed

In [2]:
from src.preprocessing import IncidentPreprocessor

# Initialize the preprocessor object
explorer = IncidentPreprocessor()

In [3]:

# Load both versions to compare
raw_df = pd.read_csv("data/incident_reports_1000.csv")
clean_df = pd.read_csv("data/incident_reports_clean.csv")

print(f"Raw Dataset Size: {raw_df.shape[0]} rows, {raw_df.shape[1]} columns")
print(f"Cleaned Dataset Size: {clean_df.shape[0]} rows, {clean_df.shape[1]} columns")
print(f"Total Rows Removed (Duplicates): {raw_df.shape[0] - clean_df.shape[0]}")

Raw Dataset Size: 1000 rows, 10 columns
Cleaned Dataset Size: 957 rows, 10 columns
Total Rows Removed (Duplicates): 43

In [4]:
print("🔍 Missing values per column in the RAW dataset:")
raw_df.isnull().sum()

🔍 Missing values per column in the RAW dataset:

incident_id       0
report_text      38
location         21
reported_by      26
department        0
severity          0
incident_type     0
report_date       0
shift             0
status            0
dtype: int64

In [5]:
print("✅ Missing values per column in the CLEAN dataset:")
clean_df.isnull().sum()

✅ Missing values per column in the CLEAN dataset:

incident_id       0
report_text      36
location         21
reported_by      25
department        0
severity          0
incident_type     0
report_date       0
shift             0
status            0
dtype: int64

In [6]:
print("--- Raw Location Varieties (First 10) ---")
print(raw_df['location'].unique()[:10])

print("\n--- Cleaned & Unified Locations ---")
print(clean_df['location'].unique()[:10])

--- Raw Location Varieties (First 10) ---
<StringArray>
[         'Platform B',  'Compressor Station',           'Tank Farm',
            'Refinery', 'Gas Processing Unit',        'Flow Station',
         'Wellhead 12',        'Control Room',    'Storage Terminal',
         'Loading Bay']
Length: 10, dtype: str

--- Cleaned & Unified Locations ---
<StringArray>
[         'PLATFORM B',  'COMPRESSOR STATION',           'TANK FARM',
            'REFINERY', 'GAS PROCESSING UNIT',        'FLOW STATION',
         'WELLHEAD 12',        'CONTROL ROOM',    'STORAGE TERMINAL',
         'LOADING BAY']
Length: 10, dtype: str

In [7]:
print("Raw Date Column Type:", raw_df['report_date'].dtype)
print("Cleaned Date Column Type:", clean_df['report_date'].dtype)

Raw Date Column Type: str
Cleaned Date Column Type: str

In [8]:
df_empty = df[df["report_text"] == ""]
df_empty_count = df_empty.shape[0]
df_empty_count

0

In [ ]:

df.isnull().sum()

incident_id       0
report_text      38
location         21
reported_by      26
department        0
severity          0
incident_type     0
report_date       0
shift             0
status            0
dtype: int64

In [27]:

clean_df.isnull().sum()

incident_id       0
report_text      36
location         21
reported_by      25
department        0
severity          0
incident_type     0
report_date       0
shift             0
status            0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(40)

In [11]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995     True
996     True
997     True
998     True
999     True
Length: 1000, dtype: bool

In [20]:
df = pd.read_csv("data/incident_reports_1000.csv")

df.head()

,incident_id,report_text,location,reported_by,department,severity,incident_type,report_date,shift,status
0,1,Pressure leak detected on Pipeline 7 during ro...,Platform B,Aisha,Instrumentation,High,Leak,2025-09-30,Day,Open
1,2,NaN,Compressor Station,Mary,Utilities,Low,Inspection,2025-12-15,Day,Closed
2,3,NaN,Tank Farm,Mary,Utilities,Medium,Slip/Fall,2025-09-09,Day,Open
3,4,Smoke observed from electrical control panel.,Refinery,Joy,Production,High,Electrical,2026-01-22,Day,Open
4,5,NaN,Gas Processing Unit,Samuel,Production,Medium,Equipment Failure,2025-02-14,Day,Closed

In [21]:
clean_df = pd.read_csv("data/incident_reports_clean.csv")

clean_df.head()

,incident_id,report_text,location,reported_by,department,severity,incident_type,report_date,shift,status
0,1,Pressure leak detected on Pipeline 7 during ro...,PLATFORM B,Aisha,INSTRUMENTATION,HIGH,LEAK,2025-09-30,Day,OPEN
1,2,NaN,COMPRESSOR STATION,Mary,UTILITIES,LOW,INSPECTION,2025-12-15,Day,CLOSED
2,3,NaN,TANK FARM,Mary,UTILITIES,MEDIUM,SLIP/FALL,2025-09-09,Day,OPEN
3,4,Smoke observed from electrical control panel.,REFINERY,Joy,PRODUCTION,HIGH,ELECTRICAL,2026-01-22,Day,OPEN
4,5,NaN,GAS PROCESSING UNIT,Samuel,PRODUCTION,MEDIUM,EQUIPMENT FAILURE,2025-02-14,Day,CLOSED

In [ ]:

text_columns = clean_df.select_dtypes(include=['object', 'string']).columns

clean_df[text_columns] = clean_df[text_columns].apply(lambda col: col.str.lower())

clean_df.head()

,incident_id,report_text,location,reported_by,department,severity,incident_type,report_date,shift,status
0,1,pressure leak detected on pipeline 7 during ro...,platform b,aisha,instrumentation,high,leak,2025-09-30,day,open
1,2,NaN,compressor station,mary,utilities,low,inspection,2025-12-15,day,closed
2,3,NaN,tank farm,mary,utilities,medium,slip/fall,2025-09-09,day,open
3,4,smoke observed from electrical control panel.,refinery,joy,production,high,electrical,2026-01-22,day,open
4,5,NaN,gas processing unit,samuel,production,medium,equipment failure,2025-02-14,day,closed